version: "2"

services:
  web-store:
    build: .
    volumes:
      - .:/app
    ports:
      - 3000:3000
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DATABASE=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    links:
      - postgres:postgres
    depends_on:
      - postgres
  postgres:
    image: postgres:9.6
    volumes:
      - /var/lib/postgres/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
